DJANGO practice/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('wiki/', include('wiki.urls')),
    path('admin/', admin.site.urls),
]

DJANGO practice/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


DJANGO practice/mysite/wiki/urls.py
from django.urls import path
from . import views

app_name = 'wiki'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<str:pk>/edit',views.edit_page, name='edit_page'),
    path('<str:pk>/save',views.save_page, name='save_page'),
    path('<str:pk>/', views.view_page, name='detail'),

]


DJANGO practice/mysite/wiki/models.py
from django.db import models


# Create your models here.



class Page(models.Model):

    title = models.CharField(max_length=64, primary_key=True)

    content = models.TextField()



    def __str__(self):

        return self.title

DJANGO practice/mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

DJANGO practice/mysite/wiki/views.py
from .models import Page
from django.views import generic
from django.shortcuts import render
from django.shortcuts import redirect

class IndexView(generic.ListView):
    template_name = 'wiki/index.html'
    context_object_name = 'pages'

    def get_queryset(self):
        return Page.objects.all()

class DetailView(generic.DetailView):
    model = Page
    template_name = 'wiki/detail.html'

    
def view_page(request, pk):
    try:
        page = Page.objects.get(pk = pk)
        return render(request, 'wiki/detail.html',{'page': page})
    except Page.DoesNotExist:
        return render(request, 'wiki/create_page.html', {'page_name': pk})

def edit_page(request, pk):
    try:
        page = Page.objects.get(pk=pk)
        content = page.content
    except Page.DoesNotExist:
        content = ''
    return render(request,'wiki/edit_page.html',
                    {
                        'page_name': pk,
                        'content': content
                    })

def save_page(request, pk):
    content = request.POST["content"]
    try:
        page = Page.objects.get(pk=pk)
        page.content = content
    except Page.DoesNotExist:
        page = Page(title=pk, content=content)
    page.save()
    return redirect ('wiki:detail', pk=pk)

DJANGO practice/mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    </head>
    <body>
{% block content %}no content{% endblock content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

DJANGO practice/mysite/polls/templates/polls/detail.html
{% extends "polls/base.html"%}
{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock content %}

DJANGO practice/mysite/polls/templates/polls/index.html
{% extends "polls/base.html"%}
{% load static %}

{% block content %}
<h2>{{title}}</h2>
<h1>Polls</h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock content %}



DJANGO practice/mysite/polls/templates/polls/results.html
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

DJANGO practice/mysite/wiki/templates/wiki/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}">

    </head>
    <body>
{% block content %}no content{% endblock content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

DJANGO practice/mysite/wiki/templates/wiki/create_page.html
{% extends 'wiki/base.html' %}
{% block content %}
    {% block contentTitle %} <h1>{{page_name}}</h1> {% endblock %}
   <p> This page does not exist.</p>
    <a class="btn btn-primary" id="Css" 
    href="{% url 'wiki:edit_page' page_name %}">Create?</a>
    {% endblock %}

DJANGO practice/mysite/wiki/templates/wiki/detail.html
{% extends "wiki/base.html" %}

{% block content %}

<h1>{{ page.title }}</h1>

{{page.content}}

<a class="btn btn-primary" id="Css" href="{% url 'wiki:index' %}">Home</a>
{% endblock %}

DJANGO practice/mysite/wiki/templates/wiki/edit_page.html
{% extends 'wiki/base.html' %}

{% block content %}
{% block contentTitle %} Edit {{page_name}} {% endblock %}
<header><h3>{{page_name}}</h3></header>

    <form method="post" action="{% url 'wiki:save_page' page_name %}">
        
        {% csrf_token %}
            <textarea id="id_content" name="content" rows="10" cols="40">
                    {{content}}
            </textarea>
            <input type="submit" value="Save">
        </form>

        <a class="btn btn-primary" 
        href="{% url 'wiki:detail' page_name %}">Cancel</a>



 {% endblock %}

DJANGO practice/mysite/wiki/templates/wiki/index.html
{% extends "wiki/base.html"%}
{% load static %}

{% block content %}
<h2>{{title}}</h2>
<h1>Wiki index</h1>


<div class="container" >
 
  {% if pages %}
  <ul  class="list-group"  id="id01" >
    {% for page in pages %}
   <li class="list" ><a href="{% url 'wiki:detail' page.title %}">{{ page.title }}</a>
  </li> 
   {% endfor %}  
    </ul> 
   {% else %}
<p>No pages are available</p> 
{% endif %} 
  
<script>
  {
    var list, i, switching, b, shouldSwitch;
    list = document.getElementById("id01");
    switching = true;
    /* Make a loop that will continue until
    no switching has been done: */
    while (switching) {
      // start by saying: no switching is done:
      switching = false;
      b = list.getElementsByTagName("LI");
      // Loop through all list-items:
      for (i = 0; i < (b.length - 1); i++) {
        // start by saying there should be no switching:
        shouldSwitch = false;
        /* check if the next item should
        switch place with the current item: */
        if (b[i].innerHTML.toLowerCase() > b[i + 1].innerHTML.toLowerCase()) {
          /* if next item is alphabetically
          lower than current item, mark as a switch
          and break the loop: */
          shouldSwitch = true;
          break;
        }
      }
      if (shouldSwitch) {
        /* If a switch has been marked, make the switch
        and mark the switch as done: */
        b[i].parentNode.insertBefore(b[i + 1], b[i]);
        switching = true;
      }
    }
  }
  </script>
</div>
{% endblock content %}